theme = "maupassant"
#theme  = "ananke"
baseURL = "https://summer4.dev"
languageCode = "zh-CN"
title = "夏四的博客"
googleAnalytics = "UA-138611423-1"

[permalinks]
    posts = "/:year/:month/:title/"
# Pagination
paginate = 10
paginatePath = "page"

[author]
  name = "夏四"
  favicon = "https://blog-1252872972.cos.ap-chengdu.myqcloud.com/avatar-face.jpg"
  email = "uyhhi1ss@gmail.com"
[params]
  subtitle = "打杂开发/Go语言(golang)程序员"
  keywords = "golang,杂谈,学习笔记,感悟,心得"
  description = "个人博客站点，记录个人的学习笔记，项目中遇到的问题，解决方案，想法杂谈"
  busuanzi = true

## 配置菜单
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5

## 评论设置
[params.utteranc]
    enable = true
    repo = "sumbrilliance/sumbrilliance.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

## 是否禁止URL Path转小写
#disablePathToLower = true

## 保持分类的原始名字（false会做转小写处理）
#preserveTaxonomyNames = true
